require:
  - rubocop-performance
  - 'test_prof/rubocop'
  - rubocop-rspec
  - rubocop-packaging

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  SuggestExtensions: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Layout/LineLength:
  Max: 125
  AllowedPatterns: ['\A#']
